version: '3.8'
services:
  java-maven-app:
    image: ${IMAGE}
    ports:
      - 8088:8088
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pass
